const Skills: { name: string; bar: number }[] = [
  { name: 'Sketch', bar: 40 },
  { name: 'Adobe XD', bar: 60 },
  { name: 'Invision', bar: 70 },
  { name: 'ReactJs', bar: 70 },
  { name: 'Next.Js', bar: 90 },
  { name: 'TypeScript', bar: 60 },
  { name: 'AWS, Dokku, GCE', bar: 40 },
  { name: 'Now - Zeit', bar: 80 },
  { name: 'Html5 / CSS3', bar: 90 },
  { name: 'Styled-Components', bar: 90 },
  { name: 'StyledJsx', bar: 90 },
  { name: 'NodeJs', bar: 50 },
  { name: 'MongoDB', bar: 70 },
  { name: 'GraphQL / Prisma', bar: 60 },
  { name: 'Apollo Server', bar: 60 },
  { name: 'Apollo Client', bar: 80 },
  { name: 'GraphQL Yoga', bar: 35 },
  { name: 'Team Work', bar: 85 },
  { name: 'Geek', bar: 100 },
  { name: 'Communication first', bar: 90 },
  { name: 'English', bar: 80 },
];

export default Skills;
